import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const company = { name: 'Hong Kong Honghui Construction Co., Limited', email: 'xiangganghonghuijianzhu@outlook.com', address: 'Shop No.41, (77W Anchor St.), G/F, Fu Tor Loy Sun Chuen (Stage 2), Kowloon, Hong Kong', registration: 'Registration number: Not provided' }
const ids = ['1493663284031-b7e3aefcae8e','1505693416388-ac5ce068fe85','1519710164239-da123dc03ef4','1517705008128-361805f42e86','1494438639946-1ebd1d20bf85','1501127122-f385ca6ddd9d','1513694203232-719a280e022f','1524758631624-e2822e304c36','1540932239986-30128078f3c5','1501183638710-841dd1904471','1497215728101-856f4ea42174','1538688423619-a81d3f23454b','1513506003901-1e6a229e2d15','1558997519-83ea9252edf8','1524758631624-e2822e304c36','1513167655288-98c7b6f2a4a3','1531058020387-3be344556be6','1512918728675-ed5a9ecdebfd','1493666438817-345a2a0c9f2a','1519947486511-46149fa0a254','1549490349-8643362247b5','1513506003901-1e6a229e2d15','1555041469-a586c61ea9bc','1540574163026-643ea20ade25','1523419409543-3b9b0f43f2a8','1507652313519-d4e9174996dd','1516455207990-7a41ce80f7ee','1556911220-bff31c812dba','1495474472287-4d71bcdd2085','1515003197210-e0cd71810b5f','1490122417551-7c003e7f9ac4','1556228453-efd6c1ff04f6','1540518614846-7eded433c457','1505693416388-ac5ce068fe85','1493809842364-78817add7ffb','1533090481720-856c6e3c1fdc','1549490349-8643362247b5','1524758631624-e2822e304c36','1493663284031-b7e3aefcae8e','1513694203232-719a280e022f','1556228578-0d85b1a4d571','1519710164239-da123dc03ef4','1517705008128-361805f42e86','1501127122-f385ca6ddd9d','1494438639946-1ebd1d20bf85','1531058020387-3be344556be6','1513506003901-1e6a229e2d15','1558997519-83ea9252edf8','1538688423619-a81d3f23454b','1513167655288-98c7b6f2a4a3','1493666438817-345a2a0c9f2a','1519947486511-46149fa0a254','1549490349-8643362247b5','1516455207990-7a41ce80f7ee','1556911220-bff31c812dba','1495474472287-4d71bcdd2085','1515003197210-e0cd71810b5f','1490122417551-7c003e7f9ac4','1556228453-efd6c1ff04f6','1540518614846-7eded433c457','1507652313519-d4e9174996dd','1493809842364-78817add7ffb','1533090481720-856c6e3c1fdc','1555041469-a586c61ea9bc','1540574163026-643ea20ade25','1523419409543-3b9b0f43f2a8','1512918728675-ed5a9ecdebfd','1558997519-83ea9252edf8','1493663284031-b7e3aefcae8e','1505693416388-ac5ce068fe85','1519710164239-da123dc03ef4','1517705008128-361805f42e86','1494438639946-1ebd1d20bf85','1501127122-f385ca6ddd9d','1513694203232-719a280e022f']
const categories = [
  { key:'furniture', name:'Furniture', names:['Sofa','Bed','Wardrobe','Dining Table','Coffee Table','Bar Cabinet','Storage Cabinet','Outdoor Table & Chairs','Folding Bed'] },
  { key:'soft', name:'Soft Furnishings', names:['Curtains','Area Rug','Cushion','Wall Art','Green Plant','Sheer Curtain','Venetian Blinds','Wallcovering','Tapestry','Bolster Cushion','Seat Cushion','Artificial Floral Arrangement','Room Divider'] },
  { key:'daily', name:'Home Essentials', names:['Bedding Four-Piece Set','Towel Set','Storage Box','Floor Mat','Quilt','Pillow','Fitted Sheet','Bath Towel','Bathrobe','Laundry Basket','Storage Case','Storage Bag','Hangers','Dust Cover','Tissue Box','House Slippers'] },
  { key:'decor', name:'Decor & Lighting', names:['Vase','Craft','Home Fragrance','Table Lamp','Floor Lamp','Wall Light','Decorative Clock','Decorative Mirror','Candle Holder','Sculptural Ornament','Wind Chime','Glass Vessel'] },
  { key:'dining', name:'Dining & Kitchen', names:['Dinnerware Set','Coffee Cup','Water Glass','Placemat','Tablecloth','Heat Mat','Fruit Bowl','Spice Jar Set'] },
  { key:'bath', name:'Bathroom', names:['Shower Curtain','Non-slip Bath Mat','Towel Rack','Bathroom Shelf','Washbasin Organizer'] }
]
const generatedImages = {
  'Sofa':'sofa-v2','Bed':'bed-v2','Wardrobe':'wardrobe-v2','Dining Table':'dining-table-v2','Coffee Table':'coffee-table-v2','Bar Cabinet':'bar-cabinet-v2','Storage Cabinet':'storage-cabinet-v2','Outdoor Table & Chairs':'outdoor-table-chairs-v2','Folding Bed':'folding-bed-v2',
  'Curtains':'curtain-v2','Area Rug':'area-rug-v2','Cushion':'cushion-v2','Wall Art':'wall-art-v2','Green Plant':'green-plant-v2','Sheer Curtain':'sheer-curtain-v2','Venetian Blinds':'venetian-blinds-v2','Wallcovering':'wallcovering-v2','Tapestry':'tapestry-v2','Bolster Cushion':'bolster-cushion-v2','Seat Cushion':'seat-cushion-v2','Artificial Floral Arrangement':'artificial-floral-v2','Room Divider':'room-divider-v2',
  'Bedding Four-Piece Set':'bedding-set-v2','Towel Set':'towel-v2','Storage Box':'storage-box-v2','Floor Mat':'floor-mat-v2','Quilt':'quilt-v2','Pillow':'pillow-v2','Fitted Sheet':'fitted-sheet-v2','Bath Towel':'bath-towel-v2','Bathrobe':'bathrobe-v2','Laundry Basket':'laundry-basket-v2','Storage Case':'storage-case-v2','Storage Bag':'storage-bag-v2','Hangers':'hangers-v2','Dust Cover':'dust-cover-v2','Tissue Box':'tissue-box-v2','House Slippers':'house-slippers-v2',
  'Vase':'vase-v2','Craft':'craft-v2','Home Fragrance':'fragrance-v2','Table Lamp':'table-lamp-v2','Floor Lamp':'floor-lamp-v2','Wall Light':'wall-light-v2','Decorative Clock':'clock-v2','Decorative Mirror':'mirror-v2','Candle Holder':'candle-holder-v2','Sculptural Ornament':'sculpture-v2','Wind Chime':'wind-chime-v2','Glass Vessel':'glass-vessel-v2',
  'Dinnerware Set':'dinnerware-v2','Coffee Cup':'coffee-cup-v2','Water Glass':'water-glass-v2','Placemat':'placemat-v2','Tablecloth':'tablecloth-v2','Heat Mat':'heat-mat-v2','Fruit Bowl':'fruit-bowl-v2','Spice Jar Set':'spice-jars-v2',
  'Shower Curtain':'shower-curtain-v2','Non-slip Bath Mat':'bath-mat-v2','Towel Rack':'towel-rack-v2','Bathroom Shelf':'bathroom-shelf-v2','Washbasin Organizer':'washbasin-organizer-v2'
}
const products = categories.flatMap((cat, ci) => cat.names.map((name, i) => ({ id:`${cat.key}-${i}`, name, category:cat.key, categoryName:cat.name, price:20 + ((i * 17 + ci * 23) % 281), color:['#e9dfd2','#d7c6b2','#d9d1c4','#d5ded9','#ded8ce'][i % 5], image:`/assets/products/${generatedImages[name]}.png` })))
const policyTitles = ['Payment','Returns & refunds','Cancellation policy','About us','Shipping policy','Track your order','Service terms','Privacy policy','DMCA']
function Header({ cartCount, onCart, onSearch }) { return <><div className="announcement">Complimentary delivery on orders over $120 <span>•</span> Designed for everyday living</div><header className="header"><a className="brand" href="#top"><span className="brand-mark">H</span><span>HONGHUI<br/><small>HOME & DAILY</small></span></a><nav>{categories.slice(0,4).map(c=><a href="#shop" key={c.key}>{c.name}</a>)}<a href="#policies">Info</a></nav><div className="actions"><button onClick={onSearch} aria-label="Search">⌕</button><a href="#account" className="account">Account</a><button className="cart-link" onClick={onCart}>Bag <b>{cartCount}</b></button></div></header></> }
function ProductCard({ product, add, buy }) { return <article className="product-card"><div className="product-photo" style={{background:product.color}}><img src={product.image} alt={product.name} loading="lazy"/><span className="tag">New</span></div><div className="product-meta"><div><h3>{product.name}</h3><p>{product.categoryName}</p></div><strong>${product.price}</strong></div><div className="product-actions"><button onClick={()=>add(product)}>Add to Cart</button><button className="buy" onClick={()=>buy(product)}>Buy Now - ${product.price}</button></div></article> }
function CartDrawer({ cart, setCart, close, checkout }) { const total=cart.reduce((s,p)=>s+p.price,0); return <div className="drawer-backdrop" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">Your selection</span><h2>Shopping bag <em>{cart.length}</em></h2></div><button onClick={close}>×</button></div>{cart.length?<><div className="cart-lines">{cart.map((p,i)=><div className="cart-line" key={`${p.id}-${i}`}><img src={p.image} alt=""/><div><h4>{p.name}</h4><p>${p.price} · quantity 1</p></div><button onClick={()=>setCart(cart.filter((_,j)=>j!==i))}>Remove</button></div>)}</div><div className="cart-total"><span>Subtotal</span><strong>${total}</strong></div><button className="primary full" onClick={checkout}>Continue to checkout</button><p className="fine">Taxes and delivery are calculated at checkout.</p></>:<div className="empty"><div className="empty-bag">○</div><p>Your bag is ready for something beautiful.</p><button className="outline" onClick={close}>Continue shopping</button></div>}</aside></div> }
function Checkout({ cart, back }) { const total=cart.reduce((s,p)=>s+p.price,0); return <main className="checkout"><button className="back" onClick={back}>← Back to shopping</button><div className="checkout-grid"><section><span className="eyebrow">Secure demo checkout</span><h1>Complete your order</h1><div className="field-grid"><label>First name<input placeholder="Your first name"/></label><label>Last name<input placeholder="Your last name"/></label></div><label>Email address<input type="email" placeholder={company.email}/></label><label>Delivery address<input placeholder="Street, district, city"/></label><h3 className="pay-title">Payment method</h3><div className="payments"><button className="payment active"><b>Pay</b>Pal</button><button className="payment">VISA</button><button className="payment">▣ Credit Card</button></div><button className="primary full" onClick={()=>alert('Demo payment redirect: no real charge was made.')}>Pay ${total} securely <span>↗</span></button><p className="fine">Frontend demo only. Choose PayPal, Visa or credit card to continue to the represented payment redirect.</p></section><aside className="order-summary"><span className="eyebrow">Order summary</span><h2>{cart.length} item{cart.length===1?'':'s'}</h2>{cart.map(p=><div className="summary-line" key={p.id}><span>{p.name}</span><strong>${p.price}</strong></div>)}<div className="summary-line total"><span>Total</span><strong>${total}</strong></div></aside></div></main> }
function Policy({ title, back }) { const terms=title==='Service terms'; return <main className="policy"><button className="back" onClick={back}>← Back to store</button><span className="eyebrow">Honghui Home & Daily</span><h1>{title}</h1><div className="policy-copy"><p>{title==='About us'?`${company.name} curates practical home goods, decorative accents, dining essentials and bathroom accessories for everyday spaces.`:`This page is part of the frontend commerce demo for ${company.name}. Please contact ${company.email} for assistance.`}</p>{terms?['Eligibility and account','Products and availability','Pricing and payment','Orders and acceptance','Delivery and tracking','Returns and exchanges','Refunds','Cancellation policy','Product care','Intellectual property','User content','Privacy','Electronic communications','Limitation of liability','Indemnification','Governing law','Contact and updates'].map((t,i)=><section key={t}><h3>{i+1}. {t}</h3><p>We aim to describe, price, fulfil and support our products accurately. Specific details shown at checkout and in the order confirmation form part of your agreement. Contact us at {company.email} if you need help with this section.</p></section>):<><h3>Company contact</h3><p>{company.name}<br/>{company.address}<br/>{company.registration}<br/>{company.email}</p></>}</div></main> }
function Account({ back }) { const [logged,setLogged]=useState(false); return <main className="policy admin"><button className="back" onClick={back}>← Back to store</button><span className="eyebrow">Honghui Home & Daily</span><h1>Customer login</h1>{logged?<div className="admin-panel"><div className="admin-stat"><span>My orders</span><strong>00</strong></div><div className="admin-stat"><span>Saved items</span><strong>00</strong></div><p>Welcome back. This customer account is a frontend demo.</p></div>:<form className="admin-form" onSubmit={e=>{e.preventDefault();setLogged(true)}}><label>Email<input type="email" placeholder="you@example.com" required /></label><label>Password<input type="password" placeholder="Your password" required /></label><button className="primary full">Log in</button><p className="fine">New here? Your account area is ready for future order tracking and saved items.</p></form>}</main> }
function Admin({ back }) { const [logged,setLogged]=useState(false); return <main className="policy admin"><button className="back" onClick={back}>← Back to store</button><span className="eyebrow">Private demo area</span><h1>Staff login</h1>{logged?<div className="admin-panel"><div className="admin-stat"><span>Orders today</span><strong>12</strong></div><div className="admin-stat"><span>Pending fulfilment</span><strong>04</strong></div><div className="admin-stat"><span>Products</span><strong>63</strong></div><div className="admin-products"><h3>Generated catalog assets</h3>{products.filter(p=>generatedImages[p.name]).map(p=><div className="summary-line" key={p.id}><span>{p.name} · {p.categoryName}</span><strong>Local image</strong></div>)}</div><p>This is a frontend-only admin demo. Connect a secure backend before using it with customer or payment data.</p></div>:<form className="admin-form" onSubmit={e=>{e.preventDefault();setLogged(true)}}><label>Email<input defaultValue="admin@honghuihome.com"/></label><label>Password<input type="password" defaultValue="HonghuiDemo2026!"/></label><button className="primary full">Sign in to demo</button><p className="fine">Demo account: admin@honghuihome.com<br/>Demo password: HonghuiDemo2026!</p></form>}</main> }
function Footer({ go }) { return <footer id="policies"><div className="footer-brand"><a className="brand" href="#top"><span className="brand-mark">H</span><span>HONGHUI<br/><small>HOME & DAILY</small></span></a><p>Everyday pieces for a more considered home.</p></div><div><h4>Shop</h4>{categories.map(c=><a href="#shop" key={c.key}>{c.name}</a>)}</div><div><h4>Customer care</h4>{policyTitles.slice(0,7).map(t=><a href="#policies" onClick={e=>{e.preventDefault();go(t)}} key={t}>{t}</a>)}</div><div><h4>Company</h4><p>{company.name}</p><p>{company.address}</p><a href={`mailto:${company.email}`}>{company.email}</a></div><div className="footer-bottom"><span>© 2026 {company.name}. All rights reserved.</span><span><a href="#policies" onClick={e=>{e.preventDefault();go('Privacy policy')}}>Privacy</a> · <a href="#policies" onClick={e=>{e.preventDefault();go('DMCA')}}>DMCA</a> · Frontend demo</span></div></footer> }
function App() { const [cart,setCart]=useState([]); const [drawer,setDrawer]=useState(false); const [page,setPage]=useState(window.location.hash==='#admin'?'admin':window.location.hash==='#account'?'account':'home'); const [filter,setFilter]=useState('all'); const [search,setSearch]=useState(false); const add=p=>{setCart(c=>[...c,p]);setDrawer(true)}; const buy=p=>{setCart(c=>[...c,p]);setPage('checkout')}; const shown=useMemo(()=>filter==='all'?products:products.filter(p=>p.category===filter),[filter]); const go=v=>setPage(v==='admin'?'admin':v==='account'?'account':policyTitles.includes(v)?v:'home'); const shell=content=><><Header cartCount={cart.length} onCart={()=>setDrawer(true)} onSearch={()=>setSearch(true)}/>{content}{drawer&&<CartDrawer cart={cart} setCart={setCart} close={()=>setDrawer(false)} checkout={()=>{setDrawer(false);setPage('checkout')}}/>}</>;
  if(page==='account')return shell(<Account back={()=>setPage('home')}/>); if(page==='admin')return shell(<Admin back={()=>setPage('home')}/>); if(page==='checkout')return shell(<Checkout cart={cart} back={()=>setPage('home')}/>); if(page!=='home')return shell(<Policy title={page} back={()=>setPage('home')}/>);
  return <div id="top">{shell(<><main><section className="hero"><div className="hero-copy"><span className="eyebrow">A softer way to live</span><h1>Objects for<br/><i>everyday rituals.</i></h1><p>Thoughtful home goods, quiet lighting and useful details for the rooms you return to.</p><a className="primary" href="#shop">Explore the collection <span>↗</span></a></div><div className="hero-image"><img src="/assets/honghui-hero-v2.png" alt="Warm neutral bedroom with home goods"/><div className="hero-note">Curated in Hong Kong<br/><b>Made for home</b></div></div></section><section className="intro"><span className="eyebrow">The Honghui edit</span><h2>Good things, well considered.</h2><p>From bed linen to bath essentials, our collection brings practical comfort and a calm point of view to everyday spaces.</p></section><section className="category-tabs" id="shop"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All pieces <small>63</small></button>{categories.map(c=><button key={c.key} className={filter===c.key?'active':''} onClick={()=>setFilter(c.key)}>{c.name} <small>{c.names.length}</small></button>)}</section>{search&&<div className="searchbar"><input autoFocus placeholder="Search the collection..."/><button onClick={()=>setSearch(false)}>Close</button></div>}<section className="product-grid">{shown.map(p=><ProductCard key={p.id} product={p} add={add} buy={buy}/>)}</section><section className="service-band"><div><span>01</span><strong>Considered quality</strong><p>Useful materials and timeless silhouettes.</p></div><div><span>02</span><strong>Here to help</strong><p>Questions? Email us anytime.</p></div></section></main><Footer go={go}/></>)}</div> }
createRoot(document.getElementById('root')).render(<App />)
